### PR TITLE
Use hashmap for menu selected action

### PR DESCRIPTION
**Pull request by Sigmanificient**

### CODE REVIEW

**Comment by GiorgosXou** [comment]
Yes to hashmaps , but shouldn't `menu_select_actions` be outside of ` __perform_menu_selected_action`?

**Comment by Sigmanificient** [comment]
It could actually to avoid recomputing the dictionnary, tho it's very small so i think the impact would be minimal

**Comment by Sigmanificient** [comment]
Would you prefer something like this?

```py
    def open_cicked_file(self):
        return self.open(self.__clicked_file)

    openfolder = partial(open, 'folder')
    open_file = partial(open, 'file')
    menu_select_actions = {
        'Open': open_clicked_file,
        'Cut': cut,
        'Delete': delete,
        'Copy': copy,
        'Paste': paste,
        'Rename': rename,
        'New File': open_file,
        'New Folder': openfolder,
        'Reload': reload,
    }

    def __perform_menu_selected_action(self, action):
        if not action:
            return False

        action_func = self.menu_select_actions.get(action)
        if not action_func:
            return False

        action_func()
        return True
```

**Comment by GiorgosXou** [comment]
Yes, preferably with `__`, because we need them as private at the momment

**Pull request merged**
