### PR TITLE
Using a pythonic project structure

### PR DESCRIPTION
**Pull request by Sigmanificient**
This is a big one. Whole project reorganization

### CODE REVIEW

**Comment by GiorgosXou** [comment]
I said 3 things [here](https://github.com/GiorgosXou/TUIFIManager/issues/42#issuecomment-1368271722) and [here](https://github.com/GiorgosXou/TUIFIManager/issues/42#issuecomment-1369822201):

> feel free to express your coding style just as you like **(but just don't change everything to your style)**...

You just auto-indent everything. That's not something that I really want. Second, when you said that *"The formatting is pretty unusual"* i said:

>  It is indeed, but I'm strict with the formating of the code. I prefer to utilize the vertical blank spaces and such the code to look like blocks of columns:

 And the 3rd thing that I've said was: 

> ... when i look at it, i look at it as a work of ascii art ...

Sorry, but that is not something that I'm willing to accept. I was clear from the begining

**Comment by Sigmanificient** [comment]
I'm not sure where did i auto-indented things tbh. Can you explain the format problem in details?

**Comment by GiorgosXou** [comment]
My fault, It was only the Imports at `file_manager.py`, the warping of code mislead me into thinking it was everything. I'll recheck it

**Comment by GiorgosXou** [comment]
I have to go for sleep it's way too late here, sorry for that.

**Comment by GiorgosXou** [comment]
Something before I fall asleep, I keep the rows between the code, 9/10 times as follows:
- 3 rows between classes
- 2 rows between functions
- 1 row  everythign inside functions

**Comment by GiorgosXou** [comment]
Let the project structure as it is, for now

**Comment by GiorgosXou** [comment]
Again, sorry for being dumb

**Pull request closed without merging**
