### PR TITLE
Refactor perfom keys function using 2 helpers

### PR DESCRIPTION
**Pull request by Sigmanificient**

### CODE REVIEW

**Comment by GiorgosXou** [comment]
I'm scared to merge right now because i was working on commands-mode, and i don't know how am i suposed to resolve the confict after, should i first push the incomplete code and then try to merge or do the opposite and merge first those and then try to resolve them

**Comment by GiorgosXou** [comment]
I'll do the first one (?)

**Comment by Sigmanificient** [comment]
You could extract your change to another branch if you want me to take a look on how to merge it. Though as it is still work in progress i think you should avoid merging it to master as it is considered as a bad git practice

**Comment by GiorgosXou** [comment]
hmm ok

**Comment by GiorgosXou** [comment]
ok i fixed it by stashing

**Pull request merged**
