### PR TITLE
Improve __main__ script

### LINKED ISSUE #65: Oopsie, version
https://github.com/GiorgosXou/TUIFIManager/blob/5b45e00ba4902318b75586a49e3dfeb1b3ce568d/TUIFIManager/__main__.py#L48

`tuifi` calls `main()` not the file `__main_.py`

### PR DESCRIPTION
**Pull request by Sigmanificient**
- fix #65 
- Split main into small function to improve variables locally
- Fix `HEIGHT` & `WIDTH` being in caps within a function despite not being constants
- Add a bit of python type hinting

### CODE REVIEW

**Comment by GiorgosXou** [comment]
I'm sorry, but it is a nop for this, there's no need for so many functions in the `__main__.py`, sometimes *"Simple is better than complex"* as the The Zen of Python says. Even if you look on ncurses examples you will most likelly see thse sttuff listed in `main()`

**Comment by GiorgosXou** [comment]
`HEIGHT` `WIDTH` don't really indicate that there is a constant variable awaiting inside the class but just that those specific values won't change during the main loop *(which... whatever I mean :P )*

**Comment by GiorgosXou** [comment]
Yeah kinda missleading to be on caps

**Comment by Sigmanificient** [comment]
Levels of indentation are not the only thing to checks for. If your function does too much thing it becomes obviously complex. In this case, the main function does the TUI initialization, the file manager initialization and the main loop. *Function should only have a single purpose*.

I don't thing this is over-exaggeration, especially here. And you would have to makes way more function, in a way more disorganized manner to make it complex to follow. this isn't the case there

**Pull request closed without merging**
