### PR TITLE
Add configuration for Nix OS

### LINKED ISSUE #72: Nix OS support
The package fail to initialize on Nix, due to a missing library `libncursesw.so.6`

```
Traceback (most recent call last):
  File "/data/dev/GiorgosXou/TUIFIManager/venv/bin/tuifi", line 5, in <module>
    from TUIFIManager.__main__ import main
  File "/data/dev/GiorgosXou/TUIFIManager/TUIFIManager/__init__.py", line 12, in <module>
    from       .TUIMenu import TUIMenu
  File "/data/dev/GiorgosXou/TUIFIManager/TUIFIManager/TUIMenu.py", line 2, in <module>
    import unicurses
  File "/data/dev/GiorgosXou/TUIFIManager/venv/lib/python3.10/site-packages/unicurses/__init__.py", line 124, in <module>
    lib1 = ctypes.CDLL(ncurses,mode=ctypes.RTLD_GLOBAL)
  File "/nix/store/hhk4wr7hwry854sq69chmrjqyi964p7y-python3-3.10.9/lib/python3.10/ctypes/__init__.py", line 374, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libncursesw.so.6: cannot open shared object file: No such file or directory
```

### PR DESCRIPTION
**Pull request by Sigmanificient**
Fix #72

### CODE REVIEW

**Comment by GiorgosXou** [comment]
> The package fail to initialize on Nix OS. As no configuration is provided, is make it hard to install properly...

The issue, isn't it because there's no any version of Ncurses installed? And if yes, is it hard to install Ncurses on Nix OS?.. Also, should there be `pkgs.python310Full` too? Isn't python supposed to be preinstalled anyways? I've really no Idea at all, I am just wondering

**Comment by GiorgosXou** [comment]
How does the nix and lock files help with the installation via pip?

**Comment by GiorgosXou** [comment]
***ok I think for the second question chatGPT answered me xD***

image

**Comment by Sigmanificient** [comment]
The more straight-forward way is: "i need this for it to work on my distro" x)

**Comment by GiorgosXou** [comment]
I'm just a bit worried about having a specific version of python `pkgs.python310Full` forcefully(?) installed by default. But if you say so, I trust you xD

**Pull request merged**
